# Generated by Django 5.0.6 on 2024-12-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_owner', '0007_room_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
