# Generated by Django 5.1.4 on 2024-12-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_owner', '0008_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelowner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hotelowner',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
